<?php

$arrayExtension = array(
"archive" => "archive",
"video" => "video",
"audio" => "audio",
"image" => "image",
"pdf" => "pdf",
"psd" => "psd",
"exe" => "exe",
"css" => "css",
"php" => "php",
"html" => "html",
"deb" => "deb",
"iso" => "cd",
"py" => "py",
"playlist" => "playlist",
"rpm" => "rpm",
"rtf" => "rtf",
"script" => "script",
"sql" => "sql",
"xml" => "xml",
"log" => "log",
"rb" => "rb",
"pres" => "pres",
"doc" => "doc",
"calc" => "calc",
"default" => "default",
"cpp" => "cpp",
"bin" => "bin",
"text" => "text"
); //en fonction de l'array, afficher l'image http://monsite.com/'.$mavariable.'.png
$archive = array("rar", "tar", "7z", "7zip", "zip", "tgz", "gz", "gzip");
$video = array("avi", "mkv", "flv", "mp4", "m4v", "wmv", "f4v", "rmvb", "m2ts", "mov", "asf", "divx", "mpg", "ts");
$audio = array("mp3", "wav", "wma", "flac");
$image = array("png", "jpeg", "jpg", "bmp", "gif", "tiff");
$pdf = array("pdf");
$psd = array("psd");
$exe = array("exe");
$css = array("css");
$php = array("php");
$html = array("html");
$deb = array("deb");
$iso = array("iso");
$py = array("py");
$playlist = array("m3u", "wpl", "asx");
$rpm = array("rpm");
$rtf = array("rtf");
$script = array("sh", "pl");
$sql = array("sql");
$xml = array("xml");
$log = array("log","nfo");
$rb = array("rb");
$pres = array("ppt","pptx");
$doc = array("doc", "docx", "odf");
$calc = array("xls", "xlsx");
$default = array("default");
$cpp = array("cpp");
$bin = array("bin", "sbin","dll");
$text = array("txt");
// $ = array("");

?>
